version: '2'
networks:
  trillian: {}
services:
  db:
    build: db/
    image: db:db
    networks:
      - trillian
  log_signer:
    build: log_signer
    image: log_signer:log_signer
    networks:
      - trillian
    ports:
      - "8092:8092"
    volumes:
      - ./config:/config
    depends_on:
      - db
  log_server:
    build: log_server
    image: log_server:log_server
    networks:
      - trillian
    ports:
      - "8091:8091"
    volumes:
      - ./config:/config
    depends_on:
      - db
  ct_server:
    build: ct_server
    ports:
      - "6962:6962"
    image: ct_server:ct_server
    networks:
      - trillian
    volumes:
      - ./config:/config
    depends_on:
      - log_signer
      - log_server
